---
- name: install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: dnsmasq.conf check
  shell: grep -q networkedinsights /etc/dnsmasq.conf && echo "yes" || echo "no"
  register: ni_exists

- name: dnsmasq.conf install
  blockinfile: 
    path: /etc/dnsmasq.conf
    block: |
      server=/colo.networkedinsights.com/192.168.200.78
      server=/colo.networkedinsights.com/192.168.200.75
  when: ni_exists.stdout == "no"

- service:
    name: dnsmasq
    state: restarted

- name: check local
  shell: grep -q "127.0.0.1" /etc/resolv.conf && echo "yes" || echo "no"
  register: local_exists

- name: ni dns
# shell: echo "nameserver 192.168.200.75" >> /etc/resolv.conf
  lineinfile: dest=/etc/resolv.conf
               insertbefore='^nameserver'
               line='nameserver 127.0.0.1'
               state=present
  when: local_exists.stdout == "no"

- name: force read only resolv.conf
  shell: chattr +i /etc/resolv.conf


