---
- name: check for pycharm
  shell: test -d /home/ryanmchale/applications/pycharm && echo "yes" || echo "no"
  register: pycharm_exists

- name: check for download
  shell: test -f /home/ryanmchale/pycharm.tar.gz && echo "yes" || echo "no"
  register: pycharm_downloaded
  when: pycharm_exists.stdout == "no"

- name: download pycharm
  shell: curl -o /home/ryanmchale/pycharm.tar.gz -LO https://download.jetbrains.com/python/pycharm-professional-2018.1.4.tar.gz 
  when: 
    - pycharm_exists.stdout == "no" 
    - pycharm_downloaded.stdout == "no"


- name: create applications
  file: path=/home/ryanmchale/applications state=directory recurse=yes
  when: pycharm_exists.stdout == "no"

- name: untar pycharm
  shell: tar xzvf /home/ryanmchale/pycharm.tar.gz -C /home/ryanmchale/applications
  when: pycharm_exists.stdout == "no"

- name: link pycharm
  file: src=/home/ryanmchale/applications/pycharm-2018.1.4 dest=/home/ryanmchale/applications/pycharm state=link
  when: pycharm_exists.stdout == "no"
     

- name: create launch entry
  become_user: root
  blockinfile:
        dest: /usr/share/applications/pycharm.desktop
        create: yes
        block: |
                [Desktop Entry]
                Name=Pycharm
                Comment=Pycharm Python IDE
                Icon=/home/ryanmchale/pycharm-2018.1.4/bin/pycharm.png
                Exec=/home/ryanmchale/pycharm-2018.1.4/bin/pycharm.sh %u
                Type=Application
                Categories=IDE
