- hosts: all
  become: true
  become_method: sudo
  become_user: root

  roles:
    - ssh
    - beakerx
    - docker

  tasks:
    - name: check git config
      shell: test -f $HOME/.gitconfig && echo "yes" || echo "no"
      become_user: rmchale
      register: git_config_exists

    - name: setup git user
      shell: git config --global user.email ryan.mchale@gmail.com 
      args:
        chdir: /home/rmchale
      become: true
      become_user: rmchale
      when: git_config_exists.stdout == "no"

    - name: setup git name
      shell: git config --global user.name "Ryan McHale"
      args:
        chdir: /home/rmchale
      become: true
      become_user: rmchale
      when: git_config_exists.stdout == "no"

    - name: ssh config install
      blockinfile: 
        marker: ""
        path: $HOME/.ssh/config
        create: yes
        block: |
          Host *
            StrictHostKeyChecking no
      become_user: rmchale

    - name: check notebooks
      shell: test -d beakerx-labs-notebooks && echo "yes" || echo "no"
      register: notebooks_exists
      become_user: rmchale

    - name: install notebooks
      shell: git clone git@gitlab.com:ryan-mchale/beakerx-labs-notebooks.git 
      become_user: rmchale
      when: notebooks_exists.stdout == "no"

    - name: hello
      shell: hostname
      register: hello

# debug example
    - debug: msg='host is = "{{ hello.stdout }}"'


