- hosts: all
  become: true
  become_method: sudo
  become_user: root

  roles:
    - ssh
    - beakerx
    - docker
    - dnsmasq

  tasks:
    - name: check git config
      shell: test -f $HOME/.gitconfig && echo "yes" || echo "no"
      become_user: rmchale
      register: git_config_exists

    - name: setup git user
      shell: git config --global user.email ryan.mchale@networkedinsights.com 
      args:
        chdir: /home/rmchale
      become: true
      become_user: rmchale
      when: git_config_exists.stdout == "no"

    - name: setup git name
      shell: git config --global user.name "Ryan McHale"
      args:
        chdir: /home/rmchale
      become: true
      become_user: rmchale
      when: git_config_exists.stdout == "no"

    - name: ssh config check
      shell: test -f $HOME/.ssh/config && echo "yes" || echo "no" 
      become_user: rmchale
      register: ssh_config_exists

    - name: dnsmasq.conf install
      blockinfile: 
        marker: ""
        path: $HOME/.ssh/config
        create: yes
        block: |
          Host *
            StrictHostKeyChecking no
      when: ssh_config_exists.stdout == "no"
      become_user: rmchale

    - name: install notebooks
      shell: git clone git@gitlab.colo.networkedinsights.com:rmchale/notebooks.git 
      become_user: rmchale
 
    - name: hello
      shell: hostname
      register: hello

# debug example
    - debug: msg='host is = "{{ hello.stdout }}"'


