#! /bin/sh

gcloud config set account ryan.mchale@networkedinsights.com
machine=$(gcloud compute instances list --project=cloud9-dev |grep mchale-beakerx |awk '{ print $5 }')
if [ -z "$machine" ]; then 
	gcloud beta compute --project "cloud9-dev" instances create "mchale-beakerx" --zone "us-central1-f" --machine-type "n1-standard-4" --subnet "cloud9-dev-subnet-a" --maintenance-policy "MIGRATE" --service-account "857626518705-compute@developer.gserviceaccount.com" --scopes "https://www.googleapis.com/auth/cloud-platform" --min-cpu-platform "Automatic" --image "debian-9-stretch-v20180307" --image-project "debian-cloud" --boot-disk-size "200" --boot-disk-type "pd-ssd" --boot-disk-device-name "mchale-beakerx"
	sleep 30
fi
ansible-playbook -v -i `gcloud compute instances list --project=cloud9-dev |grep mchale-beakerx |awk '{ print $5 }'`, beakerx.yaml