#! /bin/sh

gcloud config set account ryan.mchale@networkedinsights.com
machine=$(gcloud compute instances list --project=pioneering-tome-782 |grep mchale-beakerx |awk '{ print $5 }')
if [ -z "$machine" ]; then 
	gcloud beta compute --project "pioneering-tome-782" instances create "mchale-beakerx" --zone "us-central1-f" --machine-type "n1-standard-4" --subnet "cloud9-subnet-a" --maintenance-policy "MIGRATE"  --scopes "https://www.googleapis.com/auth/cloud-platform" --min-cpu-platform "Automatic" --image "debian-9-stretch-v20180329" --image-project "debian-cloud" --boot-disk-size "200" --boot-disk-type "pd-ssd" --boot-disk-device-name "mchale-beakerx"
	sleep 30
fi
ansible-playbook -v -i `gcloud compute instances list --project=pioneering-tome-782 |grep mchale-beakerx |awk '{ print $5 }'`, beakerx.yaml