- hosts: all
  become: true
  become_method: sudo
  become_user: root

  roles:
    - ssh
    - xfce

  tasks:
    
    - name: hello
      shell: hostname
      register: hello

# debug example
    - debug: msg='host is = "{{ hello.stdout }}"'


