---
- name: apt-get update
  apt:
    update_cache: yes
  become_user: root

- name: gpg2
  apt: name={{item}} state=installed
  with_items:
      - gpg
      - apt-transport-https
  become_user: root

- name: sublime key
  apt_key:
    url:  https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become_user: root

- name: check sublime-repo
  shell: test -f /etc/apt/sources.list.d/sublime-text.list && echo "yes" || echo "no"
  register: repo_exists

- name: sublime repo
  shell: echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
  become_user: root
  when: repo_exists.stdout == "no"

- name: apt-get update2
  apt:
    update_cache: yes
  become_user: root

- name: install sublime
  apt: name=sublime-text state=installed
  become_user: root

- name: preferences exist
  shell: test -f /home/ryanmchale/.config/sublime-text-3/Packages/User/Preferences.sublime-settings && echo "yes" || echo "no"
  register: prefs_exist

- name: create applications
  file: path=/home/ryanmchale/.config/sublime-text-3/Packages/User/Preferences.sublime-settings state=directory recurse=yes
  when: prefs_exist.stdout == "no"

- name: preferences
  blockinfile:
    dest: /home/ryanmchale/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    create: yes
    marker: ""
    block: |
        {
           "dpi_scale": 2.0,
           "font_size": 12
        }

  when: prefs_exist.stdout == "no"