---
- name: install docker packages
  apt: name={{item}} state=installed
  with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg2
       - software-properties-common

- name: docker repo check
  shell: apt-key list |grep -q -i docker && echo "yes" || echo "no"
  register: repo_key_exists

- name: install repo key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  when: repo_key_exists.stdout == "no"

- name: add repo
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  when: repo_key_exists.stdout == "no"


- name: apt-get update
  apt:
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce
    state: present